amphora/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms import ValidationError
from wtforms.validators import DataRequired, Email, EqualTo,Length
from amphora.models import User


class ValidationMixin:

    # making sure the username and email address are not already in the user table

    def validate_email(self, field):
        user = User.query.filter_by(email=field.data).first()
        if user is not None:
            raise ValidationError('This email address has already been registered.')

    def validate_username(self, field):
        user = User.query.filter_by(username=field.data).first()
        if user is not None:
            raise ValidationError('This username is already taken.')


class Login(FlaskForm):
    """
    Login Form
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log in!')


class Register(FlaskForm, ValidationMixin):
    """
    Registration Form
    """
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6,
                                                                            max=30, message='Minimum 6 characters'),
                                                     EqualTo('psw_again', message='The passwords do not match.')])
    psw_again = PasswordField('Confirm Password', validators=[DataRequired()])
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Register now!')


class Update(FlaskForm, ValidationMixin):
    """
    Update Information on Account Form
    """
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Update Email')


class ResetPswReq(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Send Request')


class ResetPsw(FlaskForm):
    password = PasswordField('Password', validators=[DataRequired()])
    psw_again = PasswordField(
        'Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

amphora/users/views.py
from flask import render_template, url_for, flash, Blueprint, redirect
from flask_login import current_user, login_user, logout_user, login_required

from amphora import db
from amphora.models import User, Story, Being, Comment
from amphora.users.forms import Login, Register, Update, ResetPsw, ResetPswReq
from amphora.users.email import send_password_reset_email

# login, logout, account, user entries

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Where users provide their information in order to register.
    """
    form = Register()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    psw=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Where users, who are already registered, can log in. The form checks for matching passwords (hashed).
    """
    form = Login()
    error_message = ''
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            error_message = 'The login details provided are incorrect.'
        elif user.psw_check(form.password.data) and user is not None:
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            error_message = 'The login details provided are incorrect.'
    return render_template('users/login.html', form=form, error_message=error_message)


@users.route('/logout')
def logout():
    """
    Where users can log out.
    """
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    Where users can view their details and update them, once logged in
    """
    form = Update()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))
    form.email.data = current_user.email
    username = current_user.username
    email = current_user.email
    return render_template('users/account.html', username=username, email=email, form=form)


@users.route('/<username>')
def user_entries(username):
    """
     Where we can see entries authored by a specific user
    """
    user = User.query.filter_by(username=username).first_or_404()
    stories = Story.query.filter_by(user=user)
    beings = Being.query.filter_by(user=user)
    comments = Comment.query.filter_by(user=user)
    return render_template('users/entries.html', user=user, beings=beings, stories=stories, comments=comments)


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_psw_req():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = ResetPswReq()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Your password reset has been requested. Please check your email inbox for the next step.')
        return redirect(url_for('users.login'))
    return render_template('users/reset_psw_req.html',
                           title='Reset Password', form=form)


@users.route('/reset_psw/<token>', methods=['GET', 'POST'])
def reset_psw(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    form = ResetPsw()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('users/psw_reset.html', form=form)

amphora/templates/users/account.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        <h1>Account</h1>

        <div class="card">
            <div class="card-image"><img src="{{ url_for('static', filename='img/amphora_card.jpg') }}">
                <ul class="collection">
                    <li class="collection-item avatar">
                        <img src="{{ current_user.avatar(128) }}" class="circle" id="circle--acct">
                        <h3 class=" title--acct"> {{ username }}</h3>
                    </li>
                </ul>

            </div>
            <div class="card-content">

                <form method="POST" action="">
                    {{form.hidden_tag()}}
                    <!-- hidden_tag protects the form against CSRF attacks.-->
                    {{form.email}}{{form.email.label}}
                    {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                    {% endfor %}<br>
                <div class="col s12 center-all">
                    {{form.submit(class="blue lighten-1 btn waves-effect waves-light")}}

                <a href="{{url_for('users.user_entries', username=username)}}"
                      class="waves-effect waves-light grey btn ">My Entries</a>
            </div>
                </form>
            </div>
        </div>

    </div>
</div>
{% endblock %}

amphora/templates/users/entries.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        <h1>Username: {{ user.username }}</h1>
        <div class="row">
            <div class="col s12 m6"><h3>Stories</h3>
                <ul class="collection">
                    {% for story in stories %}
                    <li class="collection-item avatar">
                        <i class="medium material-icons circle grey">chrome_reader_mode</i><a
                            href="{{url_for('entries.view_story', story_id=story.id)}}" class="title">{{ story.title
                        }}</a></li>
                    {% else %}
                    <li><em>No stories created yet.</em></li>

                    {% endfor %}
                </ul>
            </div>
            <div class="col s12 m6"><h3>Beings</h3>
                <ul class="collection">
                    {% for being in beings %}
                    <li class="collection-item avatar">
                        <i class="medium material-icons circle blue">accessibility</i><a
                            href="{{url_for('entries.view_being', being_id=being.id)}}" class="title">{{ being.name
                        }}</a></li>
                    {% else %}
                    <li><em>No being profiles created yet.</em></li>

                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col s12 m6"><h3>Comments</h3>
                <ul class="collection">
                    {% for comment in comments %}
                    <li class="collection-item avatar">
                        <i class="medium material-icons circle grey">comment</i>
                        <em>{{ comment.subject }}</em> in
                        {% if comment.story_id != None %}
                        <a href="{{url_for('entries.view_story', story_id=comment.story_id)}}">this entry</a>
                        {% elif comment.being_id != None %}
                        <a href="{{url_for('entries.view_being', being_id=comment.being_id)}}">this entry</a>
                        {% else %}
                        <p> an entry that was deleted by its author</p>
                        {% endif %}
                    </li>

                    {% else %}
                    <li><em>No comments posted yet.</em></li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}

amphora/templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div>
        <div class="container">
            <h1>Login</h1>

            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                {% endif %}
            {% endwith %}
            <form method="POST">
                {{ form.hidden_tag() }}
                <!-- hidden_tag protects the form against CSRF attacks.-->
                {{ form.email }}{{ form.email.label }}
                {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}<br>
                {{ form.password }}{{ form.password.label }}
                {% for error in form.password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}<br>
                <span style="color: red;">{{ error_message }}</span><br>
                {{ form.submit(class="btn waves-effect blue") }}
            </form>
            <h6><em>Please note the fields are case sensitive.</em></h6>
            <p>
                <a href="{{ url_for('users.reset_psw_req') }}">Forgot Your Password?</a>
               | First time visitor?
                <a href="{{ url_for('users.register') }}" class="">Register</a>
            </p>

        </div>
    </div>
{% endblock %}

amphora/templates/users/psw_reset.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        <h1>Reset Password</h1>
        <form method="POST" action="">
            {{form.hidden_tag()}}
            {{ form.password(size=32) }}{{ form.password.label }}<br>
            <br>
            {% for error in form.password.errors %}
            <span style="color: red;">[{{ error }}]</span>
            {% endfor %}
            {{ form.psw_again(size=32) }}{{ form.psw_again.label }}<br>
            <br>
            {% for error in form.psw_again.errors %}
            <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
            <div class="col 12 center-all">
                {{form.submit(class="btn blue waves-effect waves-light")}}
                <a href="{{ url_for('main.index' )}}" class="waves-effect btn deep-purple accent-2">
                    Return</a></div></form>
    </div>


</div>

{% endblock %}

amphora/templates/users/psw_reset_txt.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Password reset</title>
</head>
<body>
<p>Dear {{ user.username }},</p>
<p>
    To reset your password
    <a href="{{ url_for('users.reset_psw', token=token, _external=True) }}">
        click here
    </a>.
</p>
<p>As an alternative, you can paste the following link in your browser's address bar:</p>
<p>{{ url_for('users.reset_psw', token=token, _external=True) }}</p>
<p>If you have not requested a password reset simply ignore this message.</p>
<p>Sincerely,</p>
<p>Veronique, from AMPHORA</p>
</body>
</html>

amphora/templates/users/register.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
    <h1>Register</h1>


        <form method="POST">
            {{form.hidden_tag()}}
            <!-- hidden_tag protects the form against CSRF attacks.-->
            {{form.username(class="validate")}}{{form.username.label}}
            {% for error in form.username.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}<br>
            {{form.email(class="validate")}}{{form.email.label}}
             {% for error in form.email.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}<br>
            {{form.password}}{{form.password.label}}
             {% for error in form.password.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}<br>
            {{form.psw_again}}{{form.psw_again.label}}
             {% for error in form.psw_again.errors %}
            <span style="color: red;">{{ error }}</span>
            {% endfor %}<br>
            {{form.submit(onclick="$('.progress').toggle()", class="btn waves-effect blue")}}
        </form>
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
        <h6><em>Please note the fields are case sensitive.</em></h6>

        <h6>Already registered?</h6>
         <a href="{{url_for('users.login')}}" class="">Login</a></div>


</div>
{% endblock %}

amphora/templates/users/reset_psw_req.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        <h1>Reset Password Request</h1>
        <form method="POST" action="">
            {{form.hidden_tag()}}
            {{ form.email(size=64) }}{{ form.email.label }}<br>
            <br>
            {% for error in form.email.errors %}
            <span style="color: red;">[{{ error }}]</span><br>
            {% endfor %}
            <div class="col s12 center-all">
            {{form.submit(onclick="$('.progress').toggle()",class="btn blue waves-effect waves-light")}}
                <a href="{{ url_for('main.index' )}}" class="waves-effect btn deep-purple accent-2">
                            Return</a></div>
        </form>
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
    </div>
</div>
{% endblock %}