amphora/search/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    query = StringField('What are you looking for?', validators=[DataRequired()])
    submit = SubmitField("Search")

amphora/main/views.py
from flask import render_template, request, Blueprint, abort
from amphora.models import Story, Being


main = Blueprint('main', __name__)


@main.route('/')
def index():
    """
    Landing page
    """
    return render_template('index.html')


@main.route('/repo')
def repo():
    """
    Accessing the repository
    """
    page = request.args.get('page', 1, type=int)
    stories = Story.query.order_by(Story.id.desc()).paginate(page,3,False)
    beings = Being.query.order_by(Being.id.desc()).paginate(page, 3,False)
    return render_template('repo.html', stories=stories,page=page, beings=beings)


@main.route('/about')
def about():
    """
    Information about Amphora and the project
    """
    return render_template('about.html')


@main.route('/contact')
def contact():
    """
    Contact information
    """
    return render_template('contact.html')

amphora/search/views.py
from flask import render_template, Blueprint, redirect, url_for
from sqlalchemy import or_
from amphora.models import User, Category, Story, Being, Comment
from amphora.search.forms import SearchForm

searchdb = Blueprint('searchdb', __name__)


@searchdb.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        query = str(form.query.data).lower()
        return redirect(url_for('searchdb.search_req', query=query))
    return render_template('search/search.html', form=form)


@searchdb.route('/search/<query>')
def search_req(query):
    """
     Query database
    """
    categories = Category.query.filter(or_(Category.name.ilike("%{}%".format(query)), Category.description.ilike("%{}%".format(query))))
    stories = Story.query.filter(or_(Story.title.ilike("%{}%".format(query)), Story.meaning.ilike("%{}%".format(query)),
                                     Story.text.ilike("%{}%".format(query))))
    beings = Being.query.filter(or_(Being.name.ilike("%{}%".format(query)), Being.meaning.ilike("%{}%".format(query)),
                                    Being.text.ilike("%{}%".format(query))))
    users = User.query.filter(or_(User.username.ilike("%{}%".format(query)), User.email.ilike("%{}%".format(query))))
    comments = Comment.query.filter(or_(Comment.subject.ilike("%{}%".format(query)), Comment.content.ilike("%{}%".format(query))))
    return render_template('search/results.html', stories=stories, beings=beings,
                           categories=categories, users=users, comments=comments)

amphora/users/views.py
from flask import render_template, url_for, flash, Blueprint, redirect
from flask_login import current_user, login_user, logout_user, login_required

from amphora import db
from amphora.models import User, Story, Being, Comment
from amphora.users.forms import Login, Register, Update, ResetPsw, ResetPswReq
from amphora.users.email import send_password_reset_email

# login, logout, account, user entries

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Where users provide their information in order to register.
    """
    form = Register()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    psw=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Where users, who are already registered, can log in. The form checks for matching passwords (hashed).
    """
    form = Login()
    error_message = ''
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            error_message = 'The login details provided are incorrect.'
        elif user.psw_check(form.password.data) and user is not None:
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            error_message = 'The login details provided are incorrect.'
    return render_template('users/login.html', form=form, error_message=error_message)


@users.route('/logout')
def logout():
    """
    Where users can log out.
    """
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    Where users can view their details and update them, once logged in
    """
    form = Update()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))
    form.email.data = current_user.email
    username = current_user.username
    email = current_user.email
    return render_template('users/account.html', username=username, email=email, form=form)


@users.route('/<username>')
def user_entries(username):
    """
     Where we can see entries authored by a specific user
    """
    user = User.query.filter_by(username=username).first_or_404()
    stories = Story.query.filter_by(user=user)
    beings = Being.query.filter_by(user=user)
    comments = Comment.query.filter_by(user=user)
    return render_template('users/entries.html', user=user, beings=beings, stories=stories, comments=comments)


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_psw_req():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = ResetPswReq()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Your password reset has been requested. Please check your email inbox for the next step.')
        return redirect(url_for('users.login'))
    return render_template('users/reset_psw_req.html',
                           title='Reset Password', form=form)


@users.route('/reset_psw/<token>', methods=['GET', 'POST'])
def reset_psw(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    form = ResetPsw()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('users/psw_reset.html', form=form)

amphora/templates/search/results.html
{% extends "base.html" %}
{% block content%}
<div class="container">
    <h1>SEARCH RESULTS</h1>

    <ul class="collection">
        {% for user in users %}
        <li class="collection-item avatar">
            <i class="medium material-icons circle">account_circle</i>
            <a href="{{url_for('users.user_entries', username=user.username)}}" class="Title">{{ user.username }}</a>
        </li>
        {% else %}
        <li><em>USERS: No results found.</em></li>
        {% endfor %}
        {% for story in stories %}
        <li class="collection-item avatar">
            <i class="medium material-icons circle">chrome_reader_mode</i>
            <a href="{{url_for('entries.view_story', story_id=story.id)}}" class="title">{{ story.title }}</a>
        </li>
        {% else %}
        <li><em>STORIES: No results found.</em></li>
        {% endfor %}
        {% for being in beings %}
        <li class="collection-item avatar">
            <i class="medium material-icons circle blue">accessibility</i>
            <a href="{{url_for('entries.view_being', being_id=being.id)}}" class="title">{{ being.name }}</a>
        </li>
        {% else %}
        <li><em>BEINGS: No results found.</em></li>
        {% endfor %}
        {% for category in categories %}
        <li class="collection-item avatar">
            <i class="medium material-icons circle deep-purple">book</i>
            <a href="{{url_for('categories.view_category', category_id=category.id)}}" class="title">{{ category.name
                }}</a>
        </li>
        {% else %}
        <li><em>CATEGORIES: No results found.</em></li>
        {% endfor %}
        {% for comment in comments %}
        <li class="collection-item avatar">
            <i class="medium material-icons circle grey">comment</i>
            <em>{{ comment.subject }}</em> in
            {% if comment.story_id != None %}
            <a href="{{url_for('entries.view_story', story_id=comment.story_id)}}">this entry</a>
            {% elif comment.being_id != None %}
            <a href="{{url_for('entries.view_being', being_id=comment.being_id)}}">this entry</a>
            {% else %}
            <p> an entry that was deleted by its author</p>
            {% endif %}
        </li>
        {% else %}
        <li><em>COMMENTS: No results found.</em></li>
        {% endfor %}
    </ul>
    <a href="{{url_for('searchdb.search')}}" class="btn waves-effect waves-light deep-purple lighten-2">Search again</a>
</div>


{% endblock %}

amphora/templates/search/search.html
{% extends "base.html" %}
{% block content%}
<div class="container">

        <h1><i class=" material-icons">search</i> SEARCH</h1>

        <form method="POST">
            {{form.hidden_tag()}}
            {{form.query(placeholder="What are you looking for?")}}<br>
            {% for error in form.query.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            <div class="col s12 center-all">
                {{form.submit(onclick="$('.progress').toggle()", class="waves-effect btn blue")}}
                <a href="{{ url_for('main.repo')}}" class="waves-effect btn deep-purple accent-2">
            Return</a></div>


        </form>

        <div class="progress">
            <div class="indeterminate"></div>
        </div>
        </div>

{% endblock %}