amphora/entries/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired, Length, URL


class EntryStory(FlaskForm):
    title = StringField('Title', validators=[DataRequired(), Length(min=10,
                                                                    max=60)])
    text = TextAreaField('Text', validators=[DataRequired(), Length(min=20,
                                                                    max=950)])
    category_id = SelectField('Category', coerce=int)
    source = StringField('Reference (URL)', validators=[
        URL(require_tld=True, message=u'Invalid URL (example of a valid URL: http://www.website.com).')])
    meaning = TextAreaField('Associated Meaning and Values', validators=[DataRequired(), Length(min=20, max=250)])
    submit = SubmitField("Done!")


class EntryBeing(FlaskForm):
    name = StringField('Name', validators=[DataRequired(), Length(min=10,
                                                                  max=60)])
    text = TextAreaField('Text', validators=[DataRequired(), Length(min=20,
                                                                    max=950)])
    category_id = SelectField('Category', coerce=int)
    source = StringField('Reference (URL)', validators=[URL(require_tld=False,
                                            message=u'Invalid URL (example of a valid URL: http://www.website.com).')])
    meaning = TextAreaField('Associated Meaning and Values', validators=[DataRequired(), Length(min=20, max=250)])
    submit = SubmitField("Done!")


class CommentForm(FlaskForm):
    subject = StringField('Subject', validators=[DataRequired(), Length(min=10,
                                                                        max=60)])
    content = TextAreaField('Comment', validators=[DataRequired(), Length(min=20,
                                                                          max=950)])
    submit = SubmitField("Done!")

amphora/entries/views.py
from flask import render_template, url_for, Blueprint, redirect, abort
from flask_login import current_user, login_required

from amphora import db
from amphora.models import Story, Being, Category, Comment
from amphora.entries.forms import EntryStory, EntryBeing, CommentForm

entries = Blueprint('entries', __name__)


@entries.route('/new_story', methods=['GET', 'POST'])
@login_required
def create_story():
    """
    Creating a new entry of type story
    """
    form = EntryStory()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        story = Story(title=form.title.data,
                      text=form.text.data,
                      meaning=form.meaning.data,
                      category_id=form.category_id.data,
                      source=form.source.data,
                      user_id=current_user.id)

        db.session.add(story)
        db.session.commit()
        return redirect(url_for('main.repo'))
    return render_template('entries/new_story.html', form=form)


@entries.route('/new_being', methods=['GET', 'POST'])
@login_required
def create_being():
    """
    Creating a new entry of type being
    """
    form = EntryBeing()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        being = Being(name=form.name.data,
                      meaning=form.meaning.data,
                      text=form.text.data,
                      category_id=form.category_id.data,
                      source=form.source.data,
                      user_id=current_user.id)

        db.session.add(being)
        db.session.commit()
        return redirect(url_for('main.repo'))
    return render_template('entries/new_being.html', form=form)


# VIEW
@entries.route('/story/<int:story_id>', methods=['GET', 'POST'])
def view_story(story_id):
    """
     View a specific story entry
     """
    story = Story.query.get_or_404(story_id)
    comments = Comment.query.filter_by(story_id=story_id)
    form = CommentForm()
    if current_user.is_authenticated:
        if form.validate_on_submit():
            comments = Comment(subject=form.subject.data,
                               content=form.content.data,
                               story_id=story.id,
                               being_id=None,
                               user_id=current_user.id)
            db.session.add(comments)
            db.session.commit()
            print('Comment created!')
            return redirect(url_for('entries.view_story', story_id=story_id))
    return render_template('entries/stories.html', story=story, title=story.title,
                           text=story.text, meaning=story.meaning, source=story.source, comments=comments,
                           form=form)


@entries.route('/being/<int:being_id>', methods=['GET', 'POST'])
def view_being(being_id):
    """
     View a specific being entry
     """
    being = Being.query.get_or_404(being_id)
    comments = Comment.query.filter_by(being_id=being_id)
    form = CommentForm()
    if current_user.is_authenticated:
        if form.validate_on_submit():
            comments = Comment(subject=form.subject.data,
                               content=form.content.data,
                               being_id=being.id,
                               story_id=None,
                               user_id=current_user.id)
            db.session.add(comments)
            db.session.commit()
            print('Comment created!')
            return redirect(url_for('entries.view_being', being_id=being_id))
    return render_template('entries/beings.html', being=being, name=being.name,
                           text=being.text, meaning=being.meaning,
                           source=being.source, comments=comments, form=form)


@entries.route('/story/<int:story_id>/update', methods=['GET', 'POST'])
@login_required
def update_story(story_id):
    """
     Update an existing story entry, only possible if
     user is the author of the entry
     """
    story = Story.query.get_or_404(story_id)
    if story.user != current_user:
        abort(403)

    form = EntryStory()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        story.title = form.title.data
        story.text = form.text.data
        story.meaning = form.meaning.data
        story.source = form.source.data
        story.category_id = form.category_id.data
        db.session.commit()
        return redirect(url_for('entries.view_story', story_id=story_id))
    form.title.data = story.title
    form.text.data = story.text
    form.meaning.data = story.meaning
    form.category_id.data = story.category_id
    form.source.data = story.source
    title = form.title.data
    return render_template('entries/new_story.html', form=form, title=title)


@entries.route('/being/<int:being_id>/update', methods=['GET', 'POST'])
@login_required
def update_being(being_id):
    """
     Update an existing being entry, only possible if
     user is the author of the entry
     """
    being = Being.query.get_or_404(being_id)
    if being.user != current_user:
        abort(403)

    form = EntryBeing()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        being.name = form.name.data
        being.text = form.text.data
        being.meaning = form.meaning.data
        being.category_id = form.category_id.data
        being.source = form.source.data
        db.session.commit()
        return redirect(url_for('entries.view_being', being_id=being_id))
    form.name.data = being.name
    form.text.data = being.text
    form.meaning.data = being.meaning
    form.category_id.data = being.category_id
    form.source.data = being.source
    title = form.name.data
    return render_template('entries/new_being.html', form=form, title=title)


@entries.route('/story/<int:story_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_story(story_id):
    """
     Delete an existing story entry, only possible if
     user is the author of the entry
     """
    story = Story.query.get_or_404(story_id)
    if story.user != current_user:
        abort(403)
    db.session.delete(story)
    db.session.commit()
    print('Deleted the entry.')
    return redirect(url_for('main.repo'))


@entries.route('/being/<int:being_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_being(being_id):
    """
     Delete an existing being entry, only possible if
     user is the author of the entry
     """
    being = Being.query.get_or_404(being_id)
    if being.user != current_user:
        abort(403)
    db.session.delete(being)
    db.session.commit()
    print('Deleted the entry.')
    return redirect(url_for('main.repo'))

amphora/users/views.py
from flask import render_template, url_for, flash, Blueprint, redirect
from flask_login import current_user, login_user, logout_user, login_required

from amphora import db
from amphora.models import User, Story, Being, Comment
from amphora.users.forms import Login, Register, Update, ResetPsw, ResetPswReq
from amphora.users.email import send_password_reset_email

# login, logout, account, user entries

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Where users provide their information in order to register.
    """
    form = Register()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    psw=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Where users, who are already registered, can log in. The form checks for matching passwords (hashed).
    """
    form = Login()
    error_message = ''
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            error_message = 'The login details provided are incorrect.'
        elif user.psw_check(form.password.data) and user is not None:
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            error_message = 'The login details provided are incorrect.'
    return render_template('users/login.html', form=form, error_message=error_message)


@users.route('/logout')
def logout():
    """
    Where users can log out.
    """
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    Where users can view their details and update them, once logged in
    """
    form = Update()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))
    form.email.data = current_user.email
    username = current_user.username
    email = current_user.email
    return render_template('users/account.html', username=username, email=email, form=form)


@users.route('/<username>')
def user_entries(username):
    """
     Where we can see entries authored by a specific user
    """
    user = User.query.filter_by(username=username).first_or_404()
    stories = Story.query.filter_by(user=user)
    beings = Being.query.filter_by(user=user)
    comments = Comment.query.filter_by(user=user)
    return render_template('users/entries.html', user=user, beings=beings, stories=stories, comments=comments)


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_psw_req():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = ResetPswReq()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Your password reset has been requested. Please check your email inbox for the next step.')
        return redirect(url_for('users.login'))
    return render_template('users/reset_psw_req.html',
                           title='Reset Password', form=form)


@users.route('/reset_psw/<token>', methods=['GET', 'POST'])
def reset_psw(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    form = ResetPsw()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('users/psw_reset.html', form=form)

amphora/templates/entries/beings.html
{% extends "base.html" %}
{% block content%}
<div>

    <div class="container">

        <h1>{{being.name}}</h1>
        <div class="row map">
            <div class="col s12 ">
                <a href="{{url_for('main.repo')}}">Repository</a>
                <span><i class="material-icons">chevron_right</i> Being | {{ being.name }}</span>
            </div>
        </div>

        <div class="row entry-header">
            <div class="col s12 l4">
                <ul class="collection card white">
                    <li class="collection-item avatar center-all">
                        <img src="{{ being.user.avatar(36) }}" class="circle" alt="profile image">
                        <p> Entry provided by<br>
                            <a href="{{url_for('users.user_entries', username=being.user.username)}}">{{
                                being.user.username}}</a></p>
                        {% if being.user == current_user %}
                        <div class="options">
                            <a href="{{url_for('entries.update_being', being_id=being.id)}}" class="tooltipped"
                               data-position="bottom" data-tooltip="Update Entry"><i
                                    class="medium material-icons" alt="Update Entry">mode_edit</i></a>
                            <a class="modal-trigger tooltipped"
                               href="#delete_modal" data-position="bottom" data-tooltip="Delete Entry"><i
                                    class="medium material-icons" alt="Delete Entry">delete</i></a>
                        </div>
                        {% endif %}

                    </li>

                </ul>

            </div>
            <div class="col s12 l4 entry--content">
                <span>Meaning and values associated:</span> {{being.meaning}}
            </div>
            <div class="col s12 l4 entry--content"><span>Category: </span><a
                    href="{{ url_for('categories.view_category', category_id=being.category.id)}}">{{being.categories.name}}</a>
            </div>
            <div class="col s12 l4 entry--content"><span>Source:</span>
                <a href="{{source}}" target="blank"> External link</a>
            </div>


        </div>


        <div class="row">
            <div class="col s12">

                <p class="flow-text">

                    {{text}}
                </p>

            </div>
        </div>
        <div class="row">
            <div class="col s12">

                {% for comment in comments %}
                <div class="card-panel">
                    <ul class="collection">
                        <li class="collection-item avatar">
                            <img src="{{ comment.user.avatar(36) }}" class="circle" alt="profile image">
                            <p> Comment provided by<br>
                                <a href="{{url_for('users.user_entries', username=comment.user.username)}}"
                                   class="title--acct">{{
                                    comment.user.username}}</a></p>
                        </li>
                    </ul>

                    <span class="title--acct">{{ comment.subject }}</span>
                    <p> {{ comment.content }}</p>
                </div>
                {% endfor %}
            </div>
        </div>
        {% if current_user.is_authenticated %}
        <div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <h3>COMMENTS</h3>
                    <p>Comments can be viewed by everyone and <strong>CANNOT</strong> be edited or deleted. Post
                        carefully!</p>
                    <form method="POST">
                        {{form.hidden_tag()}}
                        {{form.subject.label}}{{form.subject}}
                        {% for error in form.subject.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                        {% endfor %}
                        {{form.content.label}}{{form.content(maxlength=950, class="materialize-textarea")}}
                        {% for error in form.content.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                        {% endfor %}
                        {{form.submit(onclick="$('.progress').toggle()", class="waves-effect btn blue")}}
                    </form>
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col s12">
                <div class="card-panel"><h5 class="center"><a href="{{url_for('users.login')}}">
                    Log in</a> to leave a comment.</h5></div>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col s12 center-all">

                <a href="{{url_for('main.repo')}}" class="btn waves-light waves-effect deep-purple accent-2">
                    Return</a>
            </div>
        </div>
    </div>

    <div id="delete_modal" class="modal">
        <div class="modal-content">
            <h3>Delete Entry</h3>
            <h5>Do you really want to delete this entry?</h5>
            <div class="center-all">
                <form action="{{url_for('entries.delete_being', being_id=being.id)}}" method="POST">
                    <input type="submit" class="modal-close btn waves-effect red accent-2 btn-flat" value="Delete entry">
                    <a href="#" class="modal-close btn waves-effect light-blue btn-flat">Go Back</a>
                </form>
            </div>
        </div>
    </div>


</div>
{% endblock %}

amphora/templates/entries/new_being.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        {% if title is defined %}
        <h1>{{ title }}</h1>
        {% else %}
        <h1>Create Being</h1>
        {% endif %}
        <form method="POST">
            {{form.hidden_tag()}}
            {{form.name}}{{form.name.label}}
            {% for error in form.name.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.text(maxlength=950, class="materialize-textarea")}}{{form.text.label}}
            {% for error in form.text.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.meaning(class="materialize-textarea")}}{{form.meaning.label}}
            {% for error in form.meaning.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.source}}{{form.source.label}}
            {% for error in form.source.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}<br>
            {{form.category_id(class="input-field")}}{{form.category_id.label}}
            <br>
            {% for error in form.category_id.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            <div class="col s12 center-all">
                {{form.submit(onclick="$('.progress').toggle()", class="waves-effect
                btn deep-purple accent-2")}}
                <a href="{{url_for('main.repo')}}" class="waves-effect btn blue accent-2">
                    Return</a></div>
        </form>
        <div class="progress">
            <div class="indeterminate"></div>
        </div>

    </div>
</div>
{% endblock %}

amphora/templates/entries/new_story.html
{% extends "base.html" %}
{% block content%}
<div>
    <div class="container">
        {% if title is defined %}
        <h1>{{ title }}</h1>
        {% else %}
        <h1>Create Story</h1>
        {% endif %}
        <form method="POST">
            {{form.hidden_tag()}}
            {{form.title(class="validate")}}{{form.title.label}}
            {% for error in form.title.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.text(maxlength=950, class="materialize-textarea")}}{{form.text.label}}
            {% for error in form.text.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.meaning(class="materialize-textarea")}}{{form.meaning.label}}
            {% for error in form.meaning.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            {{form.source}}{{form.source.label}}
            {% for error in form.source.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}<br>
            {{form.category_id(class="input-field")}}{{form.category_id.label}}
            {% for error in form.category_id.errors %}
            <span style="color: red;">{{ error }}</span><br>
            {% endfor %}
            <div class="col s12 center-all">
                {{form.submit(onclick="$('.progress').toggle()", class="waves-effect
                btn deep-purple accent-2")}}
                <a href="{{url_for('main.repo')}}" class="waves-effect btn blue accent-2">
                    Return</a></div>
        </form>
        <div class="progress">
            <div class="indeterminate"></div>
        </div>
    </div>
</div>
{% endblock %}

amphora/templates/entries/stories.html
{% extends "base.html" %} {% block content%}
<div>

    <div class="container">

        <h1>{{story.title}}</h1>
        <div class="row map">
            <div class="col s12">
                <a href="{{url_for('main.repo')}}">Repository</a>
                <span><i class="material-icons">chevron_right</i> Story | {{ story.title }}</span>
            </div>
        </div>
        <div class="row entry-header">
            <div class="col s12 l4">
                <ul class="collection card white">
                    <li class="collection-item avatar center-all">
                        <img src="{{ story.user.avatar(36) }}" class="circle" alt="profile image">
                        <p> Entry provided by<br>
                            <a href="{{url_for('users.user_entries', username=story.user.username)}}">{{
                                story.user.username}}</a></p>
                        {% if story.user == current_user %}
                        <div class="options">

                            <a href="{{url_for('entries.update_story', story_id=story.id)}}" class="tooltipped"
                               data-position="bottom" data-tooltip="Update Entry"><i
                                    class="medium material-icons" alt="Update Entry">mode_edit</i></a>
                            <a class="modal-trigger tooltipped"
                               href="#delete_modal" data-position="bottom" data-tooltip="Delete Entry"><i
                                    class="medium material-icons" alt="Delete Entry">delete</i></a>
                        </div>
                        {% endif %}
                    </li>
                </ul>
            </div>

            <div class="col s12 l4 entry--content">
                <span>Meaning and values associated:</span> {{story.meaning}}
            </div>
            <div class="col s12 l4 entry--content"><span>Category: </span><a
                    href="{{ url_for('categories.view_category', category_id=story.category.id)}}">{{story.categories.name}}</a>
            </div>
            <div class="col s12 l4 entry--content"><span>Source:</span>
                <a href="{{source}}" target="blank"> External link</a>
            </div>
        </div>


        <div class="row">
            <div class="col s12">
                <p class="flow-text">

                    {{text}}
                </p>

            </div>
        </div>
        <div class="row">
            <div class="col s12">

                {% for comment in comments %}
                <div class="card-panel">
                    <ul class="collection">
                        <li class="collection-item avatar">
                            <img src="{{ comment.user.avatar(36) }}" class="circle" alt="profile image">
                            <p> Comment provided by<br>
                                <a href="{{url_for('users.user_entries', username=comment.user.username)}}"
                                   class="title--acct">{{
                                    comment.user.username}}</a></p>
                        </li>
                    </ul>

                    <span class="title--acct">{{ comment.subject }}</span>
                    <p> {{ comment.content }}</p>

                </div>
                {% endfor %}
            </div>
        </div>
        {% if current_user.is_authenticated %}
        <div class="row">
            <div class="col s12">
                <div class="card-panel">
                    <h3>COMMENTS</h3>
                    <p>Comments can be viewed by everyone and <strong>CANNOT</strong> be edited or deleted. Post
                        carefully!</p>
                    <form method="POST">
                        {{form.hidden_tag()}}
                        {{form.subject.label}}{{form.subject}}
                        {% for error in form.subject.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                        {% endfor %}
                        {{form.content.label}}{{form.content(maxlength=950, class="materialize-textarea")}}
                        {% for error in form.content.errors %}
                        <span style="color: red;">{{ error }}</span><br>
                        {% endfor %}
                        {{form.submit(onclick="$('.progress').toggle()", class="waves-effect btn blue")}}
                    </form>
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <div class="row">
            <div class="col s12">
                <div class="card-panel"><h5 class="center"><a href="{{url_for('users.login')}}">
                    Log in</a> to leave a comment.</h5></div>
            </div>
        </div>
        {% endif %}
        <div class="row">
            <div class="col s12 center-all">
                <p>
                    <a href="{{url_for('main.repo')}}" class="btn waves-light waves-effect deep-purple accent-2">
                        Return</a>

                </p>
            </div>
        </div>
        <div id="delete_modal" class="modal">
            <div class="modal-content">
                <h2>Delete Entry</h2>
                <h3>Do you really want to delete this entry?</h3>
                <div class="center-all">
                    <form action="{{url_for('entries.delete_story', story_id=story.id)}}" method="POST">
                        <input type="submit" class="modal-close btn waves-effect red accent-2 btn-flat" value="Delete entry">
                        <a href="#" class="modal-close btn waves-effect light-blue btn-flat">Go Back</a></form>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}