amphora/entries/views.py
from flask import render_template, url_for, Blueprint, redirect, abort
from flask_login import current_user, login_required

from amphora import db
from amphora.models import Story, Being, Category, Comment
from amphora.entries.forms import EntryStory, EntryBeing, CommentForm

entries = Blueprint('entries', __name__)


@entries.route('/new_story', methods=['GET', 'POST'])
@login_required
def create_story():
    """
    Creating a new entry of type story
    """
    form = EntryStory()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        story = Story(title=form.title.data,
                      text=form.text.data,
                      meaning=form.meaning.data,
                      category_id=form.category_id.data,
                      source=form.source.data,
                      user_id=current_user.id)

        db.session.add(story)
        db.session.commit()
        return redirect(url_for('main.repo'))
    return render_template('entries/new_story.html', form=form)


@entries.route('/new_being', methods=['GET', 'POST'])
@login_required
def create_being():
    """
    Creating a new entry of type being
    """
    form = EntryBeing()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        being = Being(name=form.name.data,
                      meaning=form.meaning.data,
                      text=form.text.data,
                      category_id=form.category_id.data,
                      source=form.source.data,
                      user_id=current_user.id)

        db.session.add(being)
        db.session.commit()
        return redirect(url_for('main.repo'))
    return render_template('entries/new_being.html', form=form)


# VIEW
@entries.route('/story/<int:story_id>', methods=['GET', 'POST'])
def view_story(story_id):
    """
     View a specific story entry
     """
    story = Story.query.get_or_404(story_id)
    comments = Comment.query.filter_by(story_id=story_id)
    form = CommentForm()
    if current_user.is_authenticated:
        if form.validate_on_submit():
            comments = Comment(subject=form.subject.data,
                               content=form.content.data,
                               story_id=story.id,
                               being_id=None,
                               user_id=current_user.id)
            db.session.add(comments)
            db.session.commit()
            print('Comment created!')
            return redirect(url_for('entries.view_story', story_id=story_id))
    return render_template('entries/stories.html', story=story, title=story.title,
                           text=story.text, meaning=story.meaning, source=story.source, comments=comments,
                           form=form)


@entries.route('/being/<int:being_id>', methods=['GET', 'POST'])
def view_being(being_id):
    """
     View a specific being entry
     """
    being = Being.query.get_or_404(being_id)
    comments = Comment.query.filter_by(being_id=being_id)
    form = CommentForm()
    if current_user.is_authenticated:
        if form.validate_on_submit():
            comments = Comment(subject=form.subject.data,
                               content=form.content.data,
                               being_id=being.id,
                               story_id=None,
                               user_id=current_user.id)
            db.session.add(comments)
            db.session.commit()
            print('Comment created!')
            return redirect(url_for('entries.view_being', being_id=being_id))
    return render_template('entries/beings.html', being=being, name=being.name,
                           text=being.text, meaning=being.meaning,
                           source=being.source, comments=comments, form=form)


@entries.route('/story/<int:story_id>/update', methods=['GET', 'POST'])
@login_required
def update_story(story_id):
    """
     Update an existing story entry, only possible if
     user is the author of the entry
     """
    story = Story.query.get_or_404(story_id)
    if story.user != current_user:
        abort(403)

    form = EntryStory()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        story.title = form.title.data
        story.text = form.text.data
        story.meaning = form.meaning.data
        story.source = form.source.data
        story.category_id = form.category_id.data
        db.session.commit()
        return redirect(url_for('entries.view_story', story_id=story_id))
    form.title.data = story.title
    form.text.data = story.text
    form.meaning.data = story.meaning
    form.category_id.data = story.category_id
    form.source.data = story.source
    title = form.title.data
    return render_template('entries/new_story.html', form=form, title=title)


@entries.route('/being/<int:being_id>/update', methods=['GET', 'POST'])
@login_required
def update_being(being_id):
    """
     Update an existing being entry, only possible if
     user is the author of the entry
     """
    being = Being.query.get_or_404(being_id)
    if being.user != current_user:
        abort(403)

    form = EntryBeing()
    form.category_id.choices = [(i.id, i.name) for i in Category.query.all()]
    if form.validate_on_submit():
        being.name = form.name.data
        being.text = form.text.data
        being.meaning = form.meaning.data
        being.category_id = form.category_id.data
        being.source = form.source.data
        db.session.commit()
        return redirect(url_for('entries.view_being', being_id=being_id))
    form.name.data = being.name
    form.text.data = being.text
    form.meaning.data = being.meaning
    form.category_id.data = being.category_id
    form.source.data = being.source
    title = form.name.data
    return render_template('entries/new_being.html', form=form, title=title)


@entries.route('/story/<int:story_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_story(story_id):
    """
     Delete an existing story entry, only possible if
     user is the author of the entry
     """
    story = Story.query.get_or_404(story_id)
    if story.user != current_user:
        abort(403)
    db.session.delete(story)
    db.session.commit()
    print('Deleted the entry.')
    return redirect(url_for('main.repo'))


@entries.route('/being/<int:being_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_being(being_id):
    """
     Delete an existing being entry, only possible if
     user is the author of the entry
     """
    being = Being.query.get_or_404(being_id)
    if being.user != current_user:
        abort(403)
    db.session.delete(being)
    db.session.commit()
    print('Deleted the entry.')
    return redirect(url_for('main.repo'))

amphora/main/views.py
from flask import render_template, request, Blueprint, abort
from amphora.models import Story, Being


main = Blueprint('main', __name__)


@main.route('/')
def index():
    """
    Landing page
    """
    return render_template('index.html')


@main.route('/repo')
def repo():
    """
    Accessing the repository
    """
    page = request.args.get('page', 1, type=int)
    stories = Story.query.order_by(Story.id.desc()).paginate(page,3,False)
    beings = Being.query.order_by(Being.id.desc()).paginate(page, 3,False)
    return render_template('repo.html', stories=stories,page=page, beings=beings)


@main.route('/about')
def about():
    """
    Information about Amphora and the project
    """
    return render_template('about.html')


@main.route('/contact')
def contact():
    """
    Contact information
    """
    return render_template('contact.html')

amphora/search/views.py
from flask import render_template, Blueprint, redirect, url_for
from sqlalchemy import or_
from amphora.models import User, Category, Story, Being, Comment
from amphora.search.forms import SearchForm

searchdb = Blueprint('searchdb', __name__)


@searchdb.route('/search', methods=['GET', 'POST'])
def search():
    form = SearchForm()
    if form.validate_on_submit():
        query = str(form.query.data).lower()
        return redirect(url_for('searchdb.search_req', query=query))
    return render_template('search/search.html', form=form)


@searchdb.route('/search/<query>')
def search_req(query):
    """
     Query database
    """
    categories = Category.query.filter(or_(Category.name.ilike("%{}%".format(query)), Category.description.ilike("%{}%".format(query))))
    stories = Story.query.filter(or_(Story.title.ilike("%{}%".format(query)), Story.meaning.ilike("%{}%".format(query)),
                                     Story.text.ilike("%{}%".format(query))))
    beings = Being.query.filter(or_(Being.name.ilike("%{}%".format(query)), Being.meaning.ilike("%{}%".format(query)),
                                    Being.text.ilike("%{}%".format(query))))
    users = User.query.filter(or_(User.username.ilike("%{}%".format(query)), User.email.ilike("%{}%".format(query))))
    comments = Comment.query.filter(or_(Comment.subject.ilike("%{}%".format(query)), Comment.content.ilike("%{}%".format(query))))
    return render_template('search/results.html', stories=stories, beings=beings,
                           categories=categories, users=users, comments=comments)

amphora/users/views.py
from flask import render_template, url_for, flash, Blueprint, redirect
from flask_login import current_user, login_user, logout_user, login_required

from amphora import db
from amphora.models import User, Story, Being, Comment
from amphora.users.forms import Login, Register, Update, ResetPsw, ResetPswReq
from amphora.users.email import send_password_reset_email

# login, logout, account, user entries

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    """
    Where users provide their information in order to register.
    """
    form = Register()
    if form.validate_on_submit():
        user = User(email=form.email.data,
                    username=form.username.data,
                    psw=form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('users/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    """
    Where users, who are already registered, can log in. The form checks for matching passwords (hashed).
    """
    form = Login()
    error_message = ''
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            error_message = 'The login details provided are incorrect.'
        elif user.psw_check(form.password.data) and user is not None:
            login_user(user)
            return redirect(url_for('users.account'))
        else:
            error_message = 'The login details provided are incorrect.'
    return render_template('users/login.html', form=form, error_message=error_message)


@users.route('/logout')
def logout():
    """
    Where users can log out.
    """
    logout_user()
    return redirect(url_for('main.index'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """
    Where users can view their details and update them, once logged in
    """
    form = Update()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        return redirect(url_for('users.account'))
    form.email.data = current_user.email
    username = current_user.username
    email = current_user.email
    return render_template('users/account.html', username=username, email=email, form=form)


@users.route('/<username>')
def user_entries(username):
    """
     Where we can see entries authored by a specific user
    """
    user = User.query.filter_by(username=username).first_or_404()
    stories = Story.query.filter_by(user=user)
    beings = Being.query.filter_by(user=user)
    comments = Comment.query.filter_by(user=user)
    return render_template('users/entries.html', user=user, beings=beings, stories=stories, comments=comments)


@users.route('/reset_password_request', methods=['GET', 'POST'])
def reset_psw_req():
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    form = ResetPswReq()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_password_reset_email(user)
        flash('Your password reset has been requested. Please check your email inbox for the next step.')
        return redirect(url_for('users.login'))
    return render_template('users/reset_psw_req.html',
                           title='Reset Password', form=form)


@users.route('/reset_psw/<token>', methods=['GET', 'POST'])
def reset_psw(token):
    if current_user.is_authenticated:
        return redirect(url_for('users.account'))
    user = User.verify_reset_password_token(token)
    if not user:
        return redirect(url_for('main.index'))
    form = ResetPsw()
    if form.validate_on_submit():
        user.set_password(form.password.data)
        db.session.commit()
        flash('Your password has been reset.')
        return redirect(url_for('users.login'))
    return render_template('users/psw_reset.html', form=form)

amphora/templates/about.html
{% extends "base.html" %}
{% block content%}
<div class="container">
    <h1>ABOUT</h1>
    <div class="row">
        <div class="col s12 m4">
            <h5><i class="material-icons">subject</i> Definition
                of <em>amphora</em></h5>

            <div class="grey lighten-5">
                <blockquote><a href="https://www.merriam-webster.com/dictionary/amphora"
                               target="_blank">Merriam-Webster</a>

                    <ul>
                        <li>1 : an ancient Greek jar or vase with a large oval body,
                            narrow cylindrical neck, and two handles that rise almost to the level of the mouth
                        </li>
                        <li><strong>broadly : such a jar or vase used elsewhere in the ancient world</strong>
                        <li>2 : a 2-handled vessel shaped like an amphora</li>
                    </ul>
                </blockquote>
            </div>
        </div>


    <div class="col s12 m8"><h2>FAQs</h2>
        <ul>
            <li><span>Why was Amphora created?</span> Amphora is the brainchild of Veronique Savard and took form in
                the context of her Code Institute online course.
                Amphora remains your one-stop resource for information about myths, legends and incredible beings.
                You can build up your own collection of entries and review them, along with the entries provided by
                your fellows, at every visit.
            </li>
            <li><span>Can I edit someone else's entries?</span> This option is not offered at the moment.
                <strong>You can add comments to someone's entry.</strong>
                You
                can however create your own entry, which you can retrieve easily by accessing your account.
            </li>
            <li><span>Can I change my username or password?</span> Your username cannot be changed, but you can
                update your email address, which is important to keep current. You can request a password reset via
                your email address.
            </li>
            <li><span>Do I need to be logged in to update or create a category?</span> Everyone can edit and update
                categories as of now. We ask you to be respectful and include only relevant information.
            </li>


        </ul>
    </div>
</div>
</div>
{% endblock %}

amphora/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/vendors/materialize.css') }}" type="text/css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}" type="text/css"/>
    <script src="https://cdn.emailjs.com/sdk/2.2.4/email.min.js"></script>
    <script>
        (function () {
            emailjs.init("user_3AuwuMmJ74uD02b8NXmqe");
        })();
    </script>
    <title>Amphora</title>
</head>

<body>

<nav>
    <div class="nav-wrapper blue lighten-1">
        <a href="{{ url_for('main.index') }}" class="brand-logo">Amphora <i class="material-icons">local_library</i></a>
        <a href="#" data-target="amphora_navbar" class="sidenav-trigger"><i class="material-icons">menu</i></a>

        <ul class="right hide-on-med-and-down">
            <li><a href="{{ url_for('main.index') }}">Home</a></li>
            <li><a href="{{ url_for('main.repo') }}">Repository</a>
            </li>
            <li><a href="{{ url_for('searchdb.search') }}">Search</a></li>
            <li><a href="{{ url_for('main.about') }}">About</a></li>
            <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
            <li><a class="btn-floating btn-large halfway-fab deep-purple line-46 dropdown-trigger" href='#'
                   data-target='user-menu'>
                <i class="large material-icons">account_circle</i>
            </a>
                <ul id='user-menu' class='dropdown-content'>
                    {% if current_user.is_authenticated %}
                        <li class="title--acct"><a href="{{ url_for('users.account') }}"
                                                   class="waves-light blue lighten-3">Account</a>
                        </li>
                        <li class="title--acct"><a href="{{ url_for('users.logout') }}"
                                                   onclick="alert('You have been successfully logged out')"
                                                   class="waves-light">Logout</a></li>
                    {% else %}
                        <li class="title--acct"><a href="{{ url_for('users.login') }}" class="waves-light">Login</a>
                        </li>
                        <li class="title--acct"><a href="{{ url_for('users.register') }}"
                                                   class="waves-light blue lighten-3">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
        </ul>
    </div>
</nav>

<ul class="sidenav" id="amphora_navbar">
    <li><a href="{{ url_for('main.index') }}">Home</a></li>
    <li><a href="{{ url_for('main.repo') }}">Repository</a>
    </li>
    <li><a href="{{ url_for('searchdb.search') }}">Search</a></li>
    <li><a href="{{ url_for('main.about') }}">About</a></li>
    <li><a href="{{ url_for('main.contact') }}">Contact</a></li>
    {% if current_user.is_authenticated %}
        <li><a href="{{ url_for('users.account') }}" class="waves-light blue lighten-3">Account</a>
        </li>
        <li><a href="{{ url_for('users.logout') }}" onclick="alert('You have been successfully logged out')"
               class="waves-light grey lighten">Logout</a></li>
    {% else %}
        <li><a href="{{ url_for('users.login') }}" class="waves-light grey lighten-2">Login</a>
        </li>
        <li><a href="{{ url_for('users.register') }}" class="waves-light blue lighten-3">Register</a> {% endif %}
    </li>
</ul>

<main>
    {% block content %} {% endblock %}

</main>

<footer class="page-footer transparent">
    <div class="footer-copyright blue lighten-1">
        <div class="container text-darken-3 center">
            <p><a href="https://github.com/nuagesdencre" target="_blank"><img
                    src="{{ url_for('static', filename='img/GitHub-Mark-32px.png') }}" alt="Github Logo"></a></p>

        </div>
    </div>
</footer>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/vendors/materialize.js') }}"></script>
<script src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

amphora/templates/contact.html
{% extends "base.html" %}
{% block content%}
<div class="container">
    <h1> CONTACT</h1>
    <div id="contact">
        <div class="card">
            <div class="card-title">
                Send on your comments and ideas!
            </div>
            <div class="card-content">
                <form id="contact_form" method="post">

                    <input type="text" id="from_name" name="from_name"
                           placeholder="Your name or nickname"
                           required>
                    <label id="fullname">Who are you?</label>


                    <input type="text" id="where_at"
                           name="where_at" placeholder="Citizen of the world!">
                    <label id="whereat">Where are you from?</label>


                    <input type="email" autocomplete="shipping email" id="from_email" name="from_email"
                           placeholder="Example: 123@email.com"
                           required>
                    <label id="email">Email</label>

                    <textarea class="textarea" id="comments" name="comments" rows="6"
                              placeholder="Let me know what you think"></textarea>
                    <label id="message">Your Message</label><br>

                    <input id="#button" class="btn deep-purple accent-2 submit" type="submit"
                           onclick="$('.progress').toggle()" value="Send your message!">
                    <div class="progress">
                        <div class="indeterminate"></div>
                    </div>

                </form>
            </div>
        </div>
    </div>
</div>

<script>
    //emailjs
    window.onload = function () {
        document.getElementById('contact_form').addEventListener('submit', function (event) {
            event.preventDefault();
            emailjs.sendForm('gmail', 'ci_dc', this)
                .then(function () {
                    alert("Your message has been sent!");
                    $('.progress').toggle();
                    window.location = '/';
                }, function (err) {
                    alert("Send email failed!\r\n Response:\n " + JSON.stringify(err));
                });
            document.getElementById('contact_form').reset();
            return false;
        });
    };
</script>
{% endblock %}

amphora/templates/index.html
{% extends "base.html" %}
{% block content%}
<div class="container">
    <h1> Amphora</h1>
    <div class="row">
        <div class="col s12 m4 l4"><p class="flow-text"> Welcome to this repository of knowledge!</p>
            <p class="flow-text"> It is the place where you can collect, review and create entries about <strong>myths</strong>,
                <strong>legends</strong> and <strong>incredible beings</strong>.</p>
        </div>

        <div class="col s12 m4 l4 center">
            <img src="{{ url_for('static', filename='img/amphora_default.png') }}" alt="Amphora default image" class="lemon--right">
            <img src="{{ url_for('static', filename='img/amphora_main.png') }}" alt="Amphora main image" class="lemon--left">
        </div>
        <div class="col s12 m4 l4">
            <blockquote>Alice could not help her lips curling up into a smile as she began: "Do you know, I always thought
                Unicorns were fabulous monsters, too! I never saw one alive before!"
                "Well, now that we have seen each other," said the Unicorn, "if you'll believe in me, I'll believe in
                you. Is that a bargain?"
            </blockquote>
            <span><em>Lewis Carroll, Alice's Adventures in Wonderland & Through the Looking-Glass</em></span>
            <blockquote>I liked myths. They weren't adult stories and they weren't children's stories. They were better
                than that. They just were.
            </blockquote>
            <span><em>Neil Gaiman, The Ocean at the End of the Lane</em></span>
        </div>
    </div>

</div>
{% endblock %}

amphora/templates/repo.html
{% extends "base.html" %}
{% block content%}
<div class="container">
    <h1>REPOSITORY</h1>
    <div class="row">
        <div class="col s12">
            <h5><i class="material-icons">subject</i> Definition
                of <em>repository</em></h5>
            <div class="grey lighten-5">
                <blockquote><a href="https://www.merriam-webster.com/dictionary/repository" target="_blank">Merriam-Webster</a>

                    <ul>
                        <li>1 : a place, room, or container where something is deposited or stored : DEPOSITORY</li>
                        <li><strong>...</strong></li>
                        <li>3 : one that contains or stores something nonmaterial<br>
                            <em>// considered the book a repository of knowledge</em></li>
                    </ul>
                </blockquote>
            </div>
        </div>
        <div class="col s12 center-all">

            <!-- Dropdown Trigger -->
            <a class='dropdown-trigger btn waves-light waves-effect blue ' href='#' data-target='dropdown1'>
                <i class="material-icons">playlist_add</i> New Entry</a>
            <!-- Dropdown Structure -->
            <ul id='dropdown1' class='dropdown-content'>
                <li><a href="{{url_for('entries.create_story')}}">
                    Add Entry: Story</a></li>
                <li><a href="{{url_for('entries.create_being')}}">
                    Add Entry: Being</a></li>
            </ul>
            <a href="{{url_for('categories.all_categories')}}"
               class="btn waves-light waves-effect deep-purple accent-2">
                All Categories</a>
            <a href="{{ url_for('searchdb.search')}}" class="waves-effect btn white text-dark">
                <i class="tiny material-icons">search</i> Search All</a>
        </div>
    </div>
    <div class="row">
        <div class="col s12 m6">
            <h3>Stories</h3>
            {% for story in stories.items%}
            <div class="card center">
                <span class="card-title">{{story.title}}</span>
                <div class="card-content blue lighten-5">
                    <p>{{story.category}}</p><i class="material-icons">chrome_reader_mode</i>
                    <p>
                        <a href="{{ url_for('entries.view_story', story_id=story.id)}}" class="btn-flat blue-text"> Read
                            more</a>
                    </p>
                </div>
            </div>

            {% endfor %}
            <ul class="pagination ">
                {% for page_num in stories.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if stories.page == page_num %}
                <li class="disabled deep-purple lighten-5">
                    <a href="{{ url_for('main.repo', page=page_num) }}">{{ page_num
                        }}</a></li>
                {% else %}
                <li class="blue lighten-5"><a href="{{ url_for('main.repo', page=page_num) }}">{{
                    page_num }}</a></li>
                {% endif %}
            {% endfor %}
            </ul>

        </div>

        <div class="col s12 m6">
            <h3>Beings</h3>

            {% for being in beings.items%}
            <div class="card center">
                <span class="card-title">{{being.name}}</span>
                <div class="card-content blue lighten-5">
                    <p>{{being.category}}</p><i class="material-icons">accessibility</i>
                    <p><a href="{{ url_for('entries.view_being', being_id=being.id)}}" class="btn-flat blue-text">
                        Read more</a>
                    </p>
                </div>
            </div>
            {% endfor %}

            <ul class="pagination">
                {% for page_num in beings.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if beings.page == page_num %}
                <li class="disabled deep-purple lighten-5">
                    <a href="{{ url_for('main.repo', page=page_num) }}">
                        {{ page_num
                        }}</a></li>

                {% else %}
                <li class="blue lighten-5">
                    <a href="{{ url_for('main.repo', page=page_num) }}">{{ page_num }}</a></li>
                {% endif %}
                {% endfor %}
            </ul>

        </div>
    </div>


</div>
{% endblock %}